### ISSUE TITLE
Elm Make outputs invalid JavaScript despite valid Elm

### ISSUE THREAD

**Issue by imdaveho** [elm-lang/elm-platform#189] opened 2016-11-30 04:09 UTC
Smallish bug. If you try to create a union type from types declared in other modules:

```
type Example
    = Other.Type
    | Another.Type
    | Another.TypeTwo
```

This would check correctly, but would give invalid JavaScript output due to a period, `.`, in a variable name declared by the js output.

**Comment by jvoigtlaender** [comment] 2016-11-30 06:16
Please close this issue. The bug it points out is long known, and is already part of an issue reported at the compiler repository.

**Comment by jvoigtlaender** [comment] 2016-12-01 13:19
@imdaveho, would you mind closing this issue, given that it is in the wrong repository and that it is a duplicate of https://github.com/elm-lang/elm-compiler/issues/1200 anyway?

**Comment by jvoigtlaender** [comment] 2016-12-18 07:04
This issue should be closed! The new parser fixes it.

**Closed** 2016-12-22 06:28 UTC
