### ISSUE TITLE
On windows elm-reactor: failed with 'CreateDirectory 

### ISSUE THREAD

**Issue by bwanab** [elm-lang/elm-platform#39] opened 2015-03-17 13:56 UTC
full message: failed with 'CreateDirectory "C:\\Users\\allenwh\\AppData\\Roaming\\elm\\package\\elm-lang\\core\\1.1.1": invalid argument (The system cannot find the path specified.)' when sending request to

I tried creating the directories by hand but got: elm-make: CreateDirectory "C:\\Users\\allenwh\\AppData\\Roaming\\elm\\package": invalid argument (Cannot create a file when that file already exists.)

This all worked fine on OSX, but I'm forced to use windows at my work.

**Comment by evancz** [comment] 2015-06-29 22:23
Do you have admin permissions? My guess would be that you do not have permission to write to that location.

**Comment by rtfeldman** [comment] 2015-10-29 18:22
It's been 8 months without update, so I'm going to close this as Cannot Reproduce. Happy to reopen if someone can provide a http://sscce.org for this!

**Closed by rtfeldman** 2015-10-29 18:22 UTC
