### ISSUE TITLE
"I cannot find find module" imported as dependency

### ISSUE THREAD

**Issue by sergeykish** [elm-lang/elm-platform#112] opened 2015-11-20 10:34 UTC
Hello

I've been following http://tech.noredink.com/post/129641182738/building-a-live-validated-signup-form-in-elm and stuck with issue

    $ elm-make SignupForm.elm --output=elm.js

    I cannot find find module 'Effects'.

    Module 'SignupForm' is trying to import it.

    Potential problems could be:
      * Misspelled the module name
      * Need to add a source directory or new dependency to elm-package.json

Yet `./elm-stuff/packages/evancz/elm-effects/2.0.1/src/` present.
Maybe something wrong with installed packages `rm -r elm-stuff/` `elm package install`? No
What if I install package directly `elm package install evancz/elm-effects`? Works!

---

So I've created test case https://gist.github.com/sergeykish/793bc7f678eb4bb29fc4

    $ elm package install evancz/start-app
    $ du -a elm-stuff/packages/evancz/elm-effects/
    4   elm-stuff/packages/evancz/elm-effects/2.0.1/src/Native/Effects.js
    4   elm-stuff/packages/evancz/elm-effects/2.0.1/src/Native
    8   elm-stuff/packages/evancz/elm-effects/2.0.1/src/Effects.elm
    12  elm-stuff/packages/evancz/elm-effects/2.0.1/src
    4   elm-stuff/packages/evancz/elm-effects/2.0.1/elm-package.json
    4   elm-stuff/packages/evancz/elm-effects/2.0.1/README.md
    4   elm-stuff/packages/evancz/elm-effects/2.0.1/LICENSE
    4   elm-stuff/packages/evancz/elm-effects/2.0.1/.gitignore
    28  elm-stuff/packages/evancz/elm-effects/2.0.1
    28  elm-stuff/packages/evancz/elm-effects/
    $ cat > main.elm <<eof
    module TestImport where
    
    import StartApp
    import Effects
    eof
    $ elm-make main.elm --output=elm.js
    I cannot find find module 'Effects'.

    Module 'TestImport' is trying to import it.

    Potential problems could be:
      * Misspelled the module name
      * Need to add a source directory or new dependency to elm-package.json

My system

    $ uname -a
    Linux localhost 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
    $ node -v
    v5.1.0
    $ elm-make -v
    elm-make 0.16 (Elm Platform 0.16.0)
    ...

**Comment by jvoigtlaender** [comment] 2015-11-20 11:12
I don't see a bug here.

You need to do what the message said: `Need to add a source directory or new dependency to elm-package.json.`

You can do that by doing `elm package install evancz/elm-effects` or by adding `evancz/elm-effects` to `elm-package.json` and then doing just `elm package install`.

That `./elm-stuff/packages/evancz/elm-effects/2.0.1/src/` was present was just caused by the fact that it is a transitive dependency of some other package you used (likely, of `start-app`). To use `elm-effects` in your own code you still need to add it to `elm-package.json` (by one of the above two methods). If you don't declare that direct dependency of your code, you are not allowed to import the `Effects` module.

Does that clarify things?

**Comment by rtfeldman** [comment] 2015-11-24 16:05
@sergeykish Yeah, the reason you're seeing this is that Elm only lets you import dependencies explicitly listed in `elm-package.json`, so as @jvoigtlaender noted, even if another package causes them to be downloaded, they still won't be available for import until they're added to `elm-package.json`.

**Comment by jvoigtlaender** [comment] 2016-02-04 12:50
@sergeykish, close this?

**Closed** 2016-02-13 07:41 UTC
