### ISSUE TITLE
NPM install, on 32-bit Linux - Trying to launch elm-repl fails with EACCES error.

### ISSUE THREAD

**Issue by GoranM** [elm-lang/elm-platform#113] opened 2015-11-20 18:00 UTC
This is the error I get:

```
[goran@arch bin]$ ./elm-repl
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:860:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:339:9)
    at module.exports (/dev/shm/.npm/lib/node_modules/elm/binwrap.js:10:3)
    at Object.<anonymous> (/dev/shm/.npm/lib/node_modules/elm/binwrappers/elm-repl:4:55)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
```

Running with sudo produces the same error.

I installed with:

```
npm install -g elm
```

Also tried with:

```
npm install -g elm@0.16.0
```

My npm version is 3.4.0
My node version is 5.0.0

I'm guessing @rtfeldman could help me here? (was told to reference him [in a thread on Elm-Discuss](https://groups.google.com/forum/#!topic/elm-discuss/CQ5469soUTY))

**Comment by rtfeldman** [comment] 2015-11-20 18:48
Can you run this command and let me know what the output is?

```
ls -lh /usr/local/lib/node_modules/elm/binwrappers /usr/local/bin/elm*
```

**Comment by GoranM** [comment] 2015-11-20 18:51
```
[goran@arch bin]$ ls -lh /usr/local/lib/node_modules/elm/binwrappers /usr/local/bin/elm*
ls: cannot access /usr/local/lib/node_modules/elm/binwrappers: No such file or directory
ls: cannot access /usr/local/bin/elm*: No such file or directory
```

**Comment by rtfeldman** [comment] 2015-11-20 18:54
Oh...in that case:

```
which elm-repl
```

...and then if possible, re-run the previous command with the output of that replacing `/usr/local/bin` :smile:

**Comment by GoranM** [comment] 2015-11-20 19:17
It's not actually in the path (yet). Let me outline what I did in more detail:

I ran `npm install -g elm` in `/dev/shm`, and that created `/dev/shm/.npm`. I then did `cd /dev/shm/.npm/bin`, and then I ran `./elm-repl`.

Running `ls -lh` in `/dev/shm/.npm/bin` outputs:

```
lrwxrwxrwx 1 goran users 39 Nov 20 12:02 elm -> ../lib/node_modules/elm/binwrappers/elm
lrwxrwxrwx 1 goran users 44 Nov 20 12:02 elm-make -> ../lib/node_modules/elm/binwrappers/elm-make
lrwxrwxrwx 1 goran users 47 Nov 20 12:02 elm-package -> ../lib/node_modules/elm/binwrappers/elm-package
lrwxrwxrwx 1 goran users 47 Nov 20 12:02 elm-reactor -> ../lib/node_modules/elm/binwrappers/elm-reactor
lrwxrwxrwx 1 goran users 44 Nov 20 12:02 elm-repl -> ../lib/node_modules/elm/binwrappers/elm-repl
```

So, those are symlinks to the actual binaries in `/dev/shm/.npm/lib/node_modules/elm/binwrappers/elm-repl`, and if you look carefully at the error in my first post, you'll notice that the same path is referenced, so it doesn't seem to be a matter of looking in the wrong place.

**Comment by rtfeldman** [comment] 2015-11-20 19:21
> It's not actually in the path (yet)

Why wouldn't it be? The whole purpose of `npm install -g` is that it puts executables in a place that npm has set up to be on your `PATH`...

```
I ran npm install -g elm in /dev/shm, and that created /dev/shm/.npm
```

By default `.npm` is created in `~/.npm` - is `/dev/shm` your home directory?

**Comment by GoranM** [comment] 2015-11-20 19:35
I don't know. `npm install -g elm` doesn't seem to work that way on my system.

`/dev/shm` is not my home directory, it's simply a place where I ran the npm install command. My home directory is `/home/goran`, and there is a `.npm` directory there, but it only contains stuff like:

```
/home/goran/.npm/elm/
└── 0.16.0
    ├── package
    │   └── package.json
    └── package.tgz
```

There are no binaries in `/home/goran/.npm`, just more things like the above, but for other packages, along with several empty directories.

**Comment by rtfeldman** [comment] 2015-11-20 19:41
It sounds like something is messed up with your `npm` installation. If `npm install -g` isn't installing executables to your `PATH`, then it's not working properly, and if `npm install -g` isn't working properly, then `npm install -g elm` isn't going to work properly either.

Unfortunately I don't know what might be the root cause of your npm installation being messed up...but if you can get it to a point where `npm install -g elm` actually results in `elm-repl` being on your `PATH`, please let me know!

**Comment by GoranM** [comment] 2015-11-20 20:54
Running `sudo npm install -g elm` puts the binaries in `/usr/bin`, which is in the path.

```
[goran@arch shm]$ which elm-repl
/usr/bin/elm-repl
```

However, I still get the same error:

```
[goran@arch shm]$ sudo elm-repl
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:860:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:339:9)
    at module.exports (/usr/lib/node_modules/elm/binwrap.js:10:3)
    at Object.<anonymous> (/usr/lib/node_modules/elm/binwrappers/elm-repl:4:55)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
```

**Comment by rtfeldman** [comment] 2015-11-20 21:09
ok, can you run this?

```
ls -lh /usr/local/lib/node_modules/elm/binwrappers /usr/local/bin/elm*
```

**Comment by GoranM** [comment] 2015-11-20 21:14
```
[goran@arch shm]$ ls -lh /usr/lib/node_modules/elm/binwrappers /usr/bin/elm*
lrwxrwxrwx 1 root   root    39 Nov 20 15:55 /usr/bin/elm -> ../lib/node_modules/elm/binwrappers/elm
lrwxrwxrwx 1 root   root    44 Nov 20 15:55 /usr/bin/elm-make -> ../lib/node_modules/elm/binwrappers/elm-make
lrwxrwxrwx 1 root   root    47 Nov 20 15:55 /usr/bin/elm-package -> ../lib/node_modules/elm/binwrappers/elm-package
lrwxrwxrwx 1 root   root    47 Nov 20 15:55 /usr/bin/elm-reactor -> ../lib/node_modules/elm/binwrappers/elm-reactor
lrwxrwxrwx 1 root   root    44 Nov 20 15:55 /usr/bin/elm-repl -> ../lib/node_modules/elm/binwrappers/elm-repl

/usr/lib/node_modules/elm/binwrappers:
total 20K
-rwxr-xr-x 1 nobody users 112 Oct 29 01:54 elm
-rwxr-xr-x 1 nobody users 117 Oct 29 01:54 elm-make
-rwxr-xr-x 1 nobody users 120 Oct 29 01:54 elm-package
-rwxr-xr-x 1 nobody users 120 Oct 29 01:54 elm-reactor
-rwxr-xr-x 1 nobody users 117 Oct 29 01:54 elm-repl
```

**Comment by rtfeldman** [comment] 2015-11-20 21:29
What happens if you run this?
```
sudo elm-repl --help
```

**Comment by GoranM** [comment] 2015-11-20 21:39
```
[goran@arch shm]$ sudo elm-repl --help
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:860:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:339:9)
    at module.exports (/usr/lib/node_modules/elm/binwrap.js:10:3)
    at Object.<anonymous> (/usr/lib/node_modules/elm/binwrappers/elm-repl:4:55)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
```

**Comment by rtfeldman** [comment] 2015-11-21 03:03
Hm, ok...what about this?

```
ls -lh /usr/lib/node_modules/elm/Elm-Platform/0.16.0/.cabal-sandbox/bin/
```

**Comment by rtfeldman** [comment] 2015-11-21 03:11
Argh, I think I just found the culprit...somehow the 32-bit Linux binaries on our distribution server did not have their execution flags set. Our Travis build didn't catch it because Travis doesn't support 32-bit Linux, so we only have tests for the 64-bit Linux binaries. :disappointed: 

I just published revised 32-bit binaries after running `chmod +x` on them - can you try uninstalling and then reinstalling again?

**Comment by GoranM** [comment] 2015-11-21 19:09
I now get a missing library error:

```
[goran@arch shm]$ sudo elm-repl
/usr/lib/node_modules/elm/Elm-Platform/0.16.0/.cabal-sandbox/bin/elm-repl: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

**Comment by rtfeldman** [comment] 2015-11-21 19:13
Hm, now we're outside my area of expertise...@evancz any ideas? (See my previous comment for context; everything before that was diagnostic.)

**Comment by rtfeldman** [comment] 2015-11-21 19:15
@GoranM do you get the same error if you use the installation approach you mentioned initially?

**Comment by evancz** [comment] 2015-11-21 19:21
Hmm, to get the REPL working on linux, you need to have something related to ncurses and libtinfo installed. I'm not sure if I forgot to do that when I built them or if the user needs to have them and they are linked.

@GoranM, can you try googling around for the missing dependencies and installing them? I think it'll be stuff like `libtinfo-dev` though I forget exactly. I can't check for a number of hours today, so let me know when you have results! Your info + mine will let us know the full picture here.

**Comment by jvoigtlaender** [comment] 2015-11-21 19:25
The README on https://github.com/elm-lang/elm-platform has information on that. Maybe the README on the npm package page also needs to have that information.

**Comment by evancz** [comment] 2015-11-21 19:27
I'm hoping it was just my mistake and folks won't have to do that, but we'll see!

**Comment by GoranM** [comment] 2015-11-21 20:32
> do you get the same error if you use the installation approach you mentioned initially?

Yes. I guess that confirms that it's not a problem with my npm installation.

> The README on https://github.com/elm-lang/elm-platform has information on that. Maybe the README on the npm package page also needs to have that information.

If users have to manage dependencies manually, it kinda defeats the purpose of a package manager.

But, if that's the only way, I guess it's still better than wading through cabal hell ... So, yea, documenting that for npm would be appreciated.

@evancz 

It seems that there's no such thing as "libtinfo-dev" for Arch linux. However, in researching libtinfo itself, I managed to find [this thread](https://bbs.archlinux.org/viewtopic.php?pid=1108717).

Apparently, libncurses includes libtinfo on Arch linux, so this is the suggested workaround:

```
$ cd /usr/lib
$ sudo ln -s libncurses.so.5 libtinfo.so.5
```

Modified for present day:

```
$ cd /usr/lib
$ sudo ln -s libncurses++w.so.6.0 libtinfo.so.5
```

With that, elm-repl seems to work (although, it is kinda slow, especially in the beginning ... but I assume that's normal).

**Comment by evancz** [comment] 2015-11-22 22:45
Right now I think this is a Arch issue. It may be on other platforms, but I have not heard anything along those lines yet.

**Comment by rtfeldman** [comment] 2015-11-24 07:29
It seems like this is no longer an `elm-platform` issue but rather an `elm-repl` issue.

Any objections to my closing this issue and folks moving further discussion on this to the `elm-repl` repo?

**Comment by jvoigtlaender** [comment] 2015-11-24 08:09
Yes, I guess it makes sense to collect such information in the `elm-repl` repo, *if* people reading build/install instructions here in the `elm-platform` repo are told that additional requirements for running `elm-repl` are given at such-and-such place. See https://github.com/elm-lang/elm-platform/issues/115.

**Closed** 2015-11-24 15:40 UTC

**Comment by jamesnolanverran** [comment] 2016-03-01 06:53
I had the same original error message and my problem was due to permissions with my node installation. I had to uninstall and reinstall using nvm. 

http://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo/24404451#24404451

**Comment by riverdillon** [comment] 2016-06-27 01:07
I had the same issue with libtinfo, on a fresh arch install.
```$ cd /usr/lib
$ sudo ln -s libncurses++w.so.6.0 libtinfo.so.5``` seemed to fix it.

**Comment by boxofrox** [comment] 2017-01-14 02:03
Here's a non-root alternative for Arch users who used `npm install -g elm` and installed to `~/.local`.

1. Create a symbolic link for libtinfo.so.5 in elm's binwrapper folder.
```
$ cd $(which elm-repl | xargs realpath | xargs dirname)
$ ln -sf /usr/lib/libncurses++w.so.6.0 libtinfo.so.5
$ ls -la
total 5.5K
-rwxrwxr-x 1 user user 112 Oct 29  2015 elm
-rwxrwxr-x 1 user user 117 Oct 29  2015 elm-make
-rwxrwxr-x 1 user user 120 Oct 29  2015 elm-package
-rwxrwxr-x 1 user user 120 Oct 29  2015 elm-reactor
-rwxrwxr-x 1 user user 117 Oct 29  2015 elm-repl
lrwxrwxrwx 1 user user  29 Jan 13 20:05 libtinfo.so.5 -> /usr/lib/libncurses++w.so.6.0
```

2.  Edit `binwrap.js` to set the `LD_LIBRARY_PATH` environment variable so dynamic linker can find the symbolic link in (1).

```
$ cd $(which elm-repl | xargs realpath | xargs dirname)/..
$ patch -p1 <<EOF
--- a/binwrap.js  2017-01-13 20:42:18.443605608 -0500
+++ b/binwrap.js  2017-01-13 20:23:03.787045787 -0500
@@ -6,6 +6,7 @@
   var input = process.argv.slice(2);
 
   process.env.ELM_HOME = platform.shareDir;
+  process.env.LD_LIBRARY_PATH = path.join(__dirname, 'binwrappers');
 
   spawn(platform.executablePaths[executable], input, {stdio: 'inherit'})
     .on('exit', process.exit);
EOF
```

3. Profit $$$

```
$ cd ~
$ elm-repl
---- elm-repl 0.18.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
>
```

**Comment by zakora** [comment] 2017-03-24 17:47
On Fedora 25, installing `ncurses-compat-libs` solved the problem for me.

**Comment by piotr-kubica** [comment] 2017-09-24 06:50
@zakora this also solved the same problem on Fedora 24.
